const GlobalShoppingCartActions = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  UPDATE_CART_ITEM_COUNT: "UPDATE_CART_ITEM_COUNT",

  SET_PAYMENT_INFO: "SET_PAYMENT_INFO",
  SET_ADDRESS_INFO: "SET_ADDRESS_INFO",
  
  CLEAR_CART: "CLEAR_CART",
};

